version: '3.8'
services:
  mssql:
    container_name: mssql
    hostname: mssql
    image: mcr.microsoft.com/mssql/server:2017-CU29-GDR1-ubuntu-16.04
    hostname:
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_PID: 'Developer'
      MSSQL_SA_PASSWORD: 'P@ssw0rd12345'
      MSSQL_TCP_PORT: '1433'
    ports:
      - '1433:1433'
    volumes:
      - mssql-data:/var/opt/mssql
volumes:
  mssql-data:
